### ISSUE TITLE
哥，方便打包一下 debian么

### ISSUE THREAD

**Issue by fqdeng** [Qs315490/latte_kernel_6.10-rc5#1]

**Comment by Qs315490** [comment]
这是当前代码编译，还没提交上来。目前声音还是没办法驱动
https://alist.315490.xyz/d/%E4%B8%8B%E8%BD%BD/linux-image-6.10.0-rc6%2B_6.10.0-rc6-g872f208020ca-36_amd64.deb

**Comment by fqdeng** [comment]
> 这是当前代码编译，还没提交上来。目前声音还是没办法驱动 https://alist.315490.xyz/d/%E4%B8%8B%E8%BD%BD/linux-image-6.10.0-rc6%2B_6.10.0-rc6-g872f208020ca-36_amd64.deb

等你消息，我在用这块板子 开发一个flutter 看盘摸鱼工具，目前驱动已经够用了，就差摄像头 读画面 然后人脸识别了

**Comment by fqdeng** [comment]
> 这是当前代码编译，还没提交上来。目前声音还是没办法驱动 https://alist.315490.xyz/d/%E4%B8%8B%E8%BD%BD/linux-image-6.10.0-rc6%2B_6.10.0-rc6-g872f208020ca-36_amd64.deb

抽空 编译的.config 文件也留一份呗 ，这样就可以自己编译了，懒得配置

**Comment by Qs315490** [comment]
> > 这是当前代码编译，还没提交上来。目前声音还是没办法驱动 https://alist.315490.xyz/d/%E4%B8%8B%E8%BD%BD/linux-image-6.10.0-rc6%2B_6.10.0-rc6-g872f208020ca-36_amd64.deb
> 
> 抽空 编译的.config 文件也留一份呗 ，这样就可以自己编译了，懒得配置

安装完内核，`/boot` 目录下 `config-6.10-rc-6+` 就是
