### ISSUE TITLE
有遇到屏幕 现实问题么

### ISSUE THREAD

**Issue by fqdeng** [Qs315490/latte_kernel_6.10-rc5#2]
屏幕显示错乱，原本第一行的内容 跟最后一行的内容 互换了，

**Comment by Qs315490** [comment]
我手上的平板是没问题的，拍照发来看看什么情况

**Comment by fqdeng** [comment]
> 我手上的平板是没问题的，拍照发来看看什么情况

没事，我已经切到win10了， linux驱动目前看来问题还是偏多
