### ISSUE TITLE
v1.1内核，左扬声器响，右扬声器不响

### ISSUE THREAD

**Issue by RiverKawa271828** [Qs315490/latte_kernel_6.10-rc5#3]
ubuntu 22.04.4 LTS
未做声音修复的步骤，好消息是有声音了，坏消息是只有左边响

**Comment by Qs315490** [comment]
> ubuntu 22.04.4 LTS
> 未做声音修复的步骤，好消息是有声音了，坏消息是只有左边响

声音路由文件和pipewire.conf改动都是按项目fix_file/audio.md操作的吗？
Ubuntu22版文件放ucm2/cht-bsw-rt5659文件夹下

**Comment by RiverKawa271828** [comment]
对的，按照fix_file/audio.md操作完反而没声音了，回滚声音修复步骤后只有左边响

**Comment by Qs315490** [comment]
我重装系统后确实不响了，现在在排查问题

**Comment by RiverKawa271828** [comment]
好兄弟，注意身体，不急

**Comment by Qs315490** [comment]
有点棘手，不是tfa989x驱动的问题。

**Comment by Qs315490** [comment]
重新发了v1.1你试试
右扬声器如果只有左声道才会响，在终端输入
```sh
amixer -c0 sset "Amp Input1" Right
```
